version: 2.0
jobs:
  test:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers-legacy
    steps:
      - checkout:
      - run:
          name: Install requirements
          command:
            sudo pip install -r requirements.txt
      - run:
          name: Python test
          command:
            python tests.py
    #  - store_test_results:
    #     path: build/test-results


  dockerize:
   machine: true
   steps:
     - checkout
     # Login to docker
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t $DOCKER_USER/chatapp:$CIRCLE_SHA1 .

     # deploy the image
     - run: docker tag $DOCKER_USER/chatapp:$CIRCLE_SHA1 $DOCKER_USER/chatapp:latest
     - run: docker push $DOCKER_USER/chatapp:latest
workflows:
  version: 2
  feature_master:
    jobs:
      - test
      - dockerize:
          requires:
            - test

