version: 2.0
jobs:
  test:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers-legacy
    steps:
      - checkout:
      - run:
          name: Install requirements
          command:
            sudo pip install -r requirements.txt
      - run:
          name: Python test
          command:
            python tests.py
  
functional-test:
    machine: true
    steps:
      - run:
          name: curl-check
          command: curl $SSH_HOST:8000
  

deploy:
    machine: true
    steps:
      - checkout:
      #- run:
      #    name: install SSH
      #    command: apt-get install openssh-server -y
      - run:
          name: Copy files to server
          command: scp docker-compose.yml $SSH_USER@$SSH_HOST:~/

      - run:
          name: Deploy over SSH
          command: ssh $SSH_USER@$SSH_HOST "docker-compose stop && docker-compose pull && docker-compose up -d chatapp"


dockerize:
   machine: true
   steps:
     - checkout
     # Login to docker
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t $DOCKER_USER/chatapp:$CIRCLE_SHA1 .

     # deploy the image
     - run: docker tag $DOCKER_USER/chatapp:$CIRCLE_SHA1 $DOCKER_USER/chatapp:latest
     - run: docker push $DOCKER_USER/chatapp:$CIRCLE_SHA1
     - run: docker push $DOCKER_USER/chatapp:latest

workflows:
  version: 2
  feature_master:
    jobs:
      - test
      - dockerize:
          requires:
            - test
      - deploy:
         requires:
           - dockerize
      - functional-test:
         requires:
           - deploy

